//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Global {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Global() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Global", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add External Login.
        /// </summary>
        internal static string AddExternalLogin {
            get {
                return ResourceManager.GetString("AddExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Questions.
        /// </summary>
        internal static string AllQuestions {
            get {
                return ResourceManager.GetString("AllQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All subscribed tags...
        /// </summary>
        internal static string AllSubscribedTags {
            get {
                return ResourceManager.GetString("AllSubscribedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        internal static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answered.
        /// </summary>
        internal static string Answered {
            get {
                return ResourceManager.GetString("Answered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer Form.
        /// </summary>
        internal static string AnswerForm {
            get {
                return ResourceManager.GetString("AnswerForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        internal static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask!.
        /// </summary>
        internal static string AskAQuestion {
            get {
                return ResourceManager.GetString("AskAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asked.
        /// </summary>
        internal static string Asked {
            get {
                return ResourceManager.GetString("Asked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Home Page.
        /// </summary>
        internal static string BackToHomePage {
            get {
                return ResourceManager.GetString("BackToHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can subscribe to similar tags by using &quot;*&quot; charachter  &lt;br/&gt; for example: &lt;br/&gt;1. sql* &lt;br/&gt; 2. *sql &lt;br/&gt; 3. *sql*.
        /// </summary>
        internal static string BubbleForTagsSubscribe {
            get {
                return ResourceManager.GetString("BubbleForTagsSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email address.
        /// </summary>
        internal static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change or add new email address.
        /// </summary>
        internal static string ChangeEmailOrAddNewEmail {
            get {
                return ResourceManager.GetString("ChangeEmailOrAddNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Change Form.
        /// </summary>
        internal static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check that the tag exists.
        /// </summary>
        internal static string CheckSubscribe {
            get {
                return ResourceManager.GetString("CheckSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two passwords does not match..
        /// </summary>
        internal static string ConfirmPasswordNotEqualToNewPassword {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotEqualToNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to your {0} profile..
        /// </summary>
        internal static string ConnectingToProvider {
            get {
                return ResourceManager.GetString("ConnectingToProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Form.
        /// </summary>
        internal static string ConnectionForm {
            get {
                return ResourceManager.GetString("ConnectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Profile.
        /// </summary>
        internal static string CreateNewProfile {
            get {
                return ResourceManager.GetString("CreateNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask a question.
        /// </summary>
        internal static string CreateQuestion {
            get {
                return ResourceManager.GetString("CreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Answer.
        /// </summary>
        internal static string EditAnswer {
            get {
                return ResourceManager.GetString("EditAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Email.
        /// </summary>
        internal static string EditEmail {
            get {
                return ResourceManager.GetString("EditEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit My Profile.
        /// </summary>
        internal static string EditMyProfile {
            get {
                return ResourceManager.GetString("EditMyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Question.
        /// </summary>
        internal static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to answer this question in email, you should reply to this email and write your answer into the reply..
        /// </summary>
        internal static string EmailAnswerMessage {
            get {
                return ResourceManager.GetString("EmailAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email message has been sent..
        /// </summary>
        internal static string EmailHasSent {
            get {
                return ResourceManager.GetString("EmailHasSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent the email to your email address. To verify your address, please click on the link in the message..
        /// </summary>
        internal static string EmailHasSentVerifyYourAddress {
            get {
                return ResourceManager.GetString("EmailHasSentVerifyYourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is not valid..
        /// </summary>
        internal static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Registration.
        /// </summary>
        internal static string EmailReg {
            get {
                return ResourceManager.GetString("EmailReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Setting.
        /// </summary>
        internal static string EmailSetting {
            get {
                return ResourceManager.GetString("EmailSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email address has been registered to our website. Please click the following link to validate your address:.
        /// </summary>
        internal static string EmailVerificationMessage {
            get {
                return ResourceManager.GetString("EmailVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, verify your email adress.
        /// </summary>
        internal static string EmailVerifySubject {
            get {
                return ResourceManager.GetString("EmailVerifySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We couldn&apos;t find the page you requested..
        /// </summary>
        internal static string Error404Message {
            get {
                return ResourceManager.GetString("Error404Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        internal static string Error404Title {
            get {
                return ResourceManager.GetString("Error404Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing..
        /// </summary>
        internal static string ErrorInSubscribe {
            get {
                return ResourceManager.GetString("ErrorInSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        internal static string ErrorUnknownMessage {
            get {
                return ResourceManager.GetString("ErrorUnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login.
        /// </summary>
        internal static string ExternalLogin {
            get {
                return ResourceManager.GetString("ExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External profile has deleted..
        /// </summary>
        internal static string ExternalProfileIsDeleted {
            get {
                return ResourceManager.GetString("ExternalProfileIsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry for the inconveniences.
        /// </summary>
        internal static string FailedAnswerGoodbye {
            get {
                return ResourceManager.GetString("FailedAnswerGoodbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately we can not process your answer. You may use unsupported email provider or you may have deleted the id from the subject..
        /// </summary>
        internal static string FailedAnswerMessage {
            get {
                return ResourceManager.GetString("FailedAnswerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed connection.
        /// </summary>
        internal static string FailedConnection {
            get {
                return ResourceManager.GetString("FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed email reply.
        /// </summary>
        internal static string FailedEmailReply {
            get {
                return ResourceManager.GetString("FailedEmailReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed registration happened..
        /// </summary>
        internal static string FailedRegistration {
            get {
                return ResourceManager.GetString("FailedRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the service..
        /// </summary>
        internal static string FailedToConnectToTheService {
            get {
                return ResourceManager.GetString("FailedToConnectToTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed tags of the user:.
        /// </summary>
        internal static string GetAllTagToOneUserHead {
            get {
                return ResourceManager.GetString("GetAllTagToOneUserHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following tags has been subscribed by users:.
        /// </summary>
        internal static string GetSubUserHead {
            get {
                return ResourceManager.GetString("GetSubUserHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given username or password is incorrect..
        /// </summary>
        internal static string GivenUsernameOrPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("GivenUsernameOrPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give a username for your local account..
        /// </summary>
        internal static string GiveYourLocalName {
            get {
                return ResourceManager.GetString("GiveYourLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        internal static string hours {
            get {
                return ResourceManager.GetString("hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password or incorrect new password has been typed..
        /// </summary>
        internal static string IncorrectCurrentPasswordOrIncorrectNewPasswordHasTyped {
            get {
                return ResourceManager.GetString("IncorrectCurrentPasswordOrIncorrectNewPasswordHasTyped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        internal static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest questions.
        /// </summary>
        internal static string LatestQuestions {
            get {
                return ResourceManager.GetString("LatestQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest unanswered questions in your speciality..
        /// </summary>
        internal static string LatestUnansweredQuestionsWithYourFavoriteSpeciality {
            get {
                return ResourceManager.GetString("LatestUnansweredQuestionsWithYourFavoriteSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete list of questions.
        /// </summary>
        internal static string LinkTextToAllQuestionsPage {
            get {
                return ResourceManager.GetString("LinkTextToAllQuestionsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login form.
        /// </summary>
        internal static string LoginForm {
            get {
                return ResourceManager.GetString("LoginForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your local account.
        /// </summary>
        internal static string LoginWithLocalProfile {
            get {
                return ResourceManager.GetString("LoginWithLocalProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string minutes {
            get {
                return ResourceManager.GetString("minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New answer arrived, click here to show this!.
        /// </summary>
        internal static string NewAnswerArrived {
            get {
                return ResourceManager.GetString("NewAnswerArrived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New answer came for one of your subscripted tags. Here you can see the question:.
        /// </summary>
        internal static string NewAnswerEmailMessage {
            get {
                return ResourceManager.GetString("NewAnswerEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New answer came for your subscripted tag.
        /// </summary>
        internal static string NewAnswerSubject {
            get {
                return ResourceManager.GetString("NewAnswerSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has to contain at least {2} character(s)..
        /// </summary>
        internal static string NewPasswordLengthNotProper {
            get {
                return ResourceManager.GetString("NewPasswordLengthNotProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new question for one of your subscripted tags. Here you are:.
        /// </summary>
        internal static string NewQuestionEmailMessage {
            get {
                return ResourceManager.GetString("NewQuestionEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new question for your subscripted tag.
        /// </summary>
        internal static string NewQuestionSubject {
            get {
                return ResourceManager.GetString("NewQuestionSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have your email address in our system. Please enter your email address..
        /// </summary>
        internal static string NoEmail {
            get {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We don&apos;t have your email address in our system..
        /// </summary>
        internal static string NotYetEmail {
            get {
                return ResourceManager.GetString("NotYetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no subscribed tags..
        /// </summary>
        internal static string NotYetSubscribed {
            get {
                return ResourceManager.GetString("NotYetSubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now.
        /// </summary>
        internal static string Now {
            get {
                return ResourceManager.GetString("Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest first.
        /// </summary>
        internal static string OrderByReversedTime {
            get {
                return ResourceManager.GetString("OrderByReversedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest first.
        /// </summary>
        internal static string OrderByTime {
            get {
                return ResourceManager.GetString("OrderByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order by votes.
        /// </summary>
        internal static string OrderByVotes {
            get {
                return ResourceManager.GetString("OrderByVotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions and Answers.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register, if you don&apos;t have an account..
        /// </summary>
        internal static string PleaseRegisterToQuestion {
            get {
                return ResourceManager.GetString("PleaseRegisterToQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        internal static string Profil {
            get {
                return ResourceManager.GetString("Profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        internal static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionc can&apos;t be found..
        /// </summary>
        internal static string QuestionsCanNotBeFound {
            get {
                return ResourceManager.GetString("QuestionsCanNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register form.
        /// </summary>
        internal static string RegisterForm {
            get {
                return ResourceManager.GetString("RegisterForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register, if you don&apos;t have an account..
        /// </summary>
        internal static string RegisterIfYouHaveNotProfile {
            get {
                return ResourceManager.GetString("RegisterIfYouHaveNotProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registred external accounts..
        /// </summary>
        internal static string RegistredExternalLogins {
            get {
                return ResourceManager.GetString("RegistredExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related questions.
        /// </summary>
        internal static string RelatedQuestions {
            get {
                return ResourceManager.GetString("RelatedQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove external account.
        /// </summary>
        internal static string RemoveExternalLogin {
            get {
                return ResourceManager.GetString("RemoveExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reputation.
        /// </summary>
        internal static string Reputation {
            get {
                return ResourceManager.GetString("Reputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        internal static string RequiredConfirmPassword {
            get {
                return ResourceManager.GetString("RequiredConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        internal static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        internal static string RequiredNewPassword {
            get {
                return ResourceManager.GetString("RequiredNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is required..
        /// </summary>
        internal static string RequiredOldPassword {
            get {
                return ResourceManager.GetString("RequiredOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        internal static string RequiredUsername {
            get {
                return ResourceManager.GetString("RequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string seconds {
            get {
                return ResourceManager.GetString("seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separeted by commas.
        /// </summary>
        internal static string SeparetedWithCommas {
            get {
                return ResourceManager.GetString("SeparetedWithCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed tags:.
        /// </summary>
        internal static string SubscribedKeyword {
            get {
                return ResourceManager.GetString("SubscribedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully subscribed to the tag..
        /// </summary>
        internal static string SubscribedSuccess {
            get {
                return ResourceManager.GetString("SubscribedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribed user.
        /// </summary>
        internal static string SubscribedUser {
            get {
                return ResourceManager.GetString("SubscribedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful connecion happend to this provider..
        /// </summary>
        internal static string SuccessfulConnectionToThisProvider {
            get {
                return ResourceManager.GetString("SuccessfulConnectionToThisProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification was successful.
        /// </summary>
        internal static string SuccessfulEmailVerification {
            get {
                return ResourceManager.GetString("SuccessfulEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email verification was successful, welcome to the page!.
        /// </summary>
        internal static string SuccessfulEmailVerificationMessage {
            get {
                return ResourceManager.GetString("SuccessfulEmailVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest questions with {0} tag.
        /// </summary>
        internal static string TagsHeadline {
            get {
                return ResourceManager.GetString("TagsHeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have subscribed to these tags:.
        /// </summary>
        internal static string ThisSubscribeTags {
            get {
                return ResourceManager.GetString("ThisSubscribeTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ask a question, you have to login..
        /// </summary>
        internal static string ToQuestionYouNeedToLogIn {
            get {
                return ResourceManager.GetString("ToQuestionYouNeedToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to enter tags for a question..
        /// </summary>
        internal static string Tv1 {
            get {
                return ResourceManager.GetString("Tv1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter no more than 5 tags..
        /// </summary>
        internal static string Tv2 {
            get {
                return ResourceManager.GetString("Tv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a tag is 25 charachters..
        /// </summary>
        internal static string Tv3 {
            get {
                return ResourceManager.GetString("Tv3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful email verification.
        /// </summary>
        internal static string UnsuccessfulEmailVerification {
            get {
                return ResourceManager.GetString("UnsuccessfulEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email verification was unsuccessful, please try again!.
        /// </summary>
        internal static string UnsuccessfulEmailVerificationMessage {
            get {
                return ResourceManager.GetString("UnsuccessfulEmailVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to ask the question.
        /// </summary>
        internal static string UnsuccessfulQuestionAsk {
            get {
                return ResourceManager.GetString("UnsuccessfulQuestionAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions answered by user..
        /// </summary>
        internal static string UserAnsweredQuestions {
            get {
                return ResourceManager.GetString("UserAnsweredQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User menu.
        /// </summary>
        internal static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is reserved, please pick another..
        /// </summary>
        internal static string UsernameIsReserved {
            get {
                return ResourceManager.GetString("UsernameIsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions by user..
        /// </summary>
        internal static string UserQuestions {
            get {
                return ResourceManager.GetString("UserQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification.
        /// </summary>
        internal static string Verification {
            get {
                return ResourceManager.GetString("Verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votes.
        /// </summary>
        internal static string Vote {
            get {
                return ResourceManager.GetString("Vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already voted for this answer..
        /// </summary>
        internal static string YouAlreadyVotedForThisAnswer {
            get {
                return ResourceManager.GetString("YouAlreadyVotedForThisAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already voted for this question..
        /// </summary>
        internal static string YouAlreadyVotedForThisQuestion {
            get {
                return ResourceManager.GetString("YouAlreadyVotedForThisQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in with this username:.
        /// </summary>
        internal static string YouAreLoggedInWithThisUsername {
            get {
                return ResourceManager.GetString("YouAreLoggedInWithThisUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you can&apos;t ask a question..
        /// </summary>
        internal static string YouCantQuestion {
            get {
                return ResourceManager.GetString("YouCantQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t vote for your own answer..
        /// </summary>
        internal static string YouCantVoteForYourOwnAnswer {
            get {
                return ResourceManager.GetString("YouCantVoteForYourOwnAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t vote for your own question.
        /// </summary>
        internal static string YouCantVoteForYourOwnQuestion {
            get {
                return ResourceManager.GetString("YouCantVoteForYourOwnQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to give content for an answer..
        /// </summary>
        internal static string YouHaveToGiveContentForAnAnswer {
            get {
                return ResourceManager.GetString("YouHaveToGiveContentForAnAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to give content for a question..
        /// </summary>
        internal static string YouHaveToGiveContentForAQuestion {
            get {
                return ResourceManager.GetString("YouHaveToGiveContentForAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to give at least 25 character long, at most 25000 character long answer..
        /// </summary>
        internal static string YouHaveToGiveProperLengthContentForAnAnswer {
            get {
                return ResourceManager.GetString("YouHaveToGiveProperLengthContentForAnAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to give at least 25 character long, at most 25000 character long question.
        /// </summary>
        internal static string YouHaveToGiveProperLengthContentForAQuestion {
            get {
                return ResourceManager.GetString("YouHaveToGiveProperLengthContentForAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to give at least 12character long, at most 120 character long title..
        /// </summary>
        internal static string YouHaveToGiveProperLengthTitleForAQuestion {
            get {
                return ResourceManager.GetString("YouHaveToGiveProperLengthTitleForAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to giva a title for the question..
        /// </summary>
        internal static string YouHaveToGiveTitleForAQuestion {
            get {
                return ResourceManager.GetString("YouHaveToGiveTitleForAQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to login before vote..
        /// </summary>
        internal static string YouHaveToLoginBeforeVote {
            get {
                return ResourceManager.GetString("YouHaveToLoginBeforeVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouMustVerifyEmail.
        /// </summary>
        internal static string YouMustVerifyEmail {
            get {
                return ResourceManager.GetString("YouMustVerifyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has changed..
        /// </summary>
        internal static string YourPasswordIsChanged {
            get {
                return ResourceManager.GetString("YourPasswordIsChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has setted..
        /// </summary>
        internal static string YourPasswordIsSetted {
            get {
                return ResourceManager.GetString("YourPasswordIsSetted", resourceCulture);
            }
        }
    }
}
